#!/bin/bash
echo $0
set -xe
python replaceFieldNameFromRequestBody.py -i cybersource-rest-spec.json > replaceFieldLogs.log
set +xe
rm replaceFieldLogs.log


# Delete the previously generated SDK code

rm -rf ../docs
rm -rf ../lib/cybersource_rest_client/api
rm -rf ../lib/cybersource_rest_client/models
rm -rf ../spec
rm ../lib/cybersource_rest_client.rb

# Command to generate SDK

java -jar swagger-codegen-cli-2.2.3.jar generate -t cybersource-ruby-template -i cybersource-rest-spec-ruby.json -l ruby -o ../ -c cybersource-ruby-config.json

sed -i "s|select_header_content_type(\["\'"application\/json;charset=utf-8|select_header_content_type(\["\'"\*\/\*|g" ../lib/cybersource_rest_client/api/secure_file_share_api.rb
#sed -i 's/$/\r/' ../lib/cybersource_rest_client/api/secure_file_share_api.rb

# to rename error__links to error_links

sed -i "s|cybersource_rest_client/models/error__links|cybersource_rest_client/models/error_links|g" ../lib/cybersource_rest_client.rb

# to rename long file name

mv ../lib/cybersource_rest_client/models/ptsv2payments_processing_information_authorization_options_initiator_merchant_initiated_transaction.rb ../lib/cybersource_rest_client/models/ptsv2payments_merchant_initiated_transaction.rb

mv ../lib/cybersource_rest_client/models/reporting_v3_interchange_clearing_level_details_get200_response_interchange_clearing_level_details.rb ../lib/cybersource_rest_client/models/reporting_get200_response_interchange_clearing_level_details.rb

# mv ../lib/cybersource_rest_client/models/risk_v1_authentication_exemptions_post201_response_consumer_authentication_information_strong_authentication.rb ../lib/cybersource_rest_client/models/risk_v1_authentication_exemptions_consumer_authentication_information_strong_authentication.r

# mv ../lib/cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response__embedded__embedded_instrument_identifier.rb   ../lib/cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_embedded_instrument_identifier.rb

mv ../lib/cybersource_rest_client/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier_processing_information_authorization_options_initiator_merchant_initiated_transaction.rb  ../lib/cybersource_rest_client/models/tmsv2customers__embedded_merchant_initiated_transaction.rb

# If this line fails, it is because of the long filepath. Either manually change the filename OR reduce the directory nesting on the repository.

mv ../lib/cybersource_rest_client/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier_processing_information_authorization_options_initiator.rb ../lib/cybersource_rest_client/models/tmsv2customers__embedded_authorization_options_initiator.rb

# mv ../lib/cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response__embedded_buyer_information_personal_identification.rb   ../lib/cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response_personal_identification.rb

# mv ../lib/cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response__embedded_processing_information_bank_transfer_options.rb  ../lib/cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response_bank_transfer_options.rb

# mv ../lib/cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response__embedded_merchant_information_merchant_descriptor.rb   ../lib/cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response_merchant_descriptor.rb

# mv ../lib/cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response__embedded_buyer_information_issued_by.rb ../lib/cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response_buyer_information_issued_by.rb

# mv ../lib/cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response__embedded_instrument_identifier.rb ../lib/cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response_instrument_identifier.rb

# mv ../lib/cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response__embedded_merchant_information.rb  ../lib/cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response_merchant_information.rb

mv ../lib/cybersource_rest_client/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier__links_payment_instruments.rb  ../lib/cybersource_rest_client/models/tmsv2customers__embedded_payment_instruments.rb

mv ../lib/cybersource_rest_client/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier_processing_information.rb  ../lib/cybersource_rest_client/models/tmsv2customers__embedded_processing_information.rb

mv ../lib/cybersource_rest_client/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier_processing_information_authorization_options.rb  ../lib/cybersource_rest_client/models/tmsv2customers__embedded_authorization_options.rb

mv ../lib/cybersource_rest_client/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier_tokenized_card.rb  ../lib/cybersource_rest_client/models/tmsv2customers__embedded_tokenized_card.rb

mv ../lib/cybersource_rest_client/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier_tokenized_card_card.rb  ../lib/cybersource_rest_client/models/tmsv2customers__embedded_tokenized_card_card.rb

mv ../lib/cybersource_rest_client/models/pts_v2_payments_post201_response_consumer_authentication_information_strong_authentication_issuer_information.rb ../lib/cybersource_rest_client/models/pts_v2_payments_post201_response_consumer_authentication_information_issuer_information.rb

mv ../docs/Ptsv2paymentsProcessingInformationAuthorizationOptionsInitiatorMerchantInitiatedTransaction.md ../docs/Ptsv2paymentsMerchantInitiatedTransaction.md

mv ../docs/Tmsv2customersEmbeddedDefaultPaymentInstrumentEmbeddedInstrumentIdentifierProcessingInformationAuthorizationOptionsInitiatorMerchantInitiatedTransaction.md ../docs/Tmsv2customersEmbeddedMerchantInitiatedTransaction.md

mv ../spec/models/ptsv2payments_processing_information_authorization_options_initiator_merchant_initiated_transaction_spec.rb ../spec/models/ptsv2payments_merchant_initiated_transaction_spec.rb

mv ../spec/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier_processing_information_authorization_options_initiator_merchant_initiated_transaction_spec.rb ../spec/models/tmsv2customers__embedded_merchant_initiated_transaction_spec.rb

mv ../lib/cybersource_rest_client/models/risk_v1_address_verifications_post201_response_address_verification_information_standard_address_address1.rb ../lib/cybersource_rest_client/models/risk_v1_address_verifications_post201_response_address1.rb

# mv ../lib/cybersource_rest_client/models/risk_v1_export_compliance_inquiries_post201_response_export_compliance_information_watch_list_matches.rb ../lib/cybersource_rest_client/models/risk_v1_export_compliance_inquiries_post201_response_watch_list_matches.rb

mv ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_common_merchant_descriptor_information.rb ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_merchant_descriptor_information.rb

mv ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_features_card_not_present.rb ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_card_not_present.rb

mv ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_features_card_not_present_installment.rb ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_card_not_present_installment.rb

mv ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_features_card_not_present_payouts.rb ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_card_not_present_payouts.rb

mv ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_features_card_not_present_payouts_currencies.rb ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_card_not_present_payouts_currencies.rb

mv ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_features_card_not_present_processors.rb ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_card_not_present_processors.rb

mv ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_features_card_present_processors.rb ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_card_present_processors.rb

mv ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_features_card_present.rb ../lib/cybersource_rest_client/models/payment_products_card_processing_configuration_information_card_present.rb

mv ../lib/cybersource_rest_client/models/payment_products_e_check_configuration_information_configurations_features_account_validation_service.rb ../lib/cybersource_rest_client/models/payment_products_e_check_configuration_information_account_validation_service.rb

mv ../lib/cybersource_rest_client/models/payment_products_e_check_configuration_information_configurations_features_account_validation_service_internal_only.rb ../lib/cybersource_rest_client/models/payment_products_e_check_configuration_information_account_validation_service_internal_only.rb

mv ../lib/cybersource_rest_client/models/payment_products_e_check_configuration_information_configurations_features_account_validation_service_processors.rb ../lib/cybersource_rest_client/models/payment_products_e_check_configuration_information_account_validation_service_processors.rb

mv ../lib/cybersource_rest_client/models/payment_products_payer_authentication_configuration_information_configurations_card_types_j_cbj_secure.rb ../lib/cybersource_rest_client/models/payment_products_payer_authentication_configuration_information_card_types_j_cbj_secure.rb

mv ../lib/cybersource_rest_client/models/payment_products_payer_authentication_configuration_information_configurations_card_types_verified_by_visa.rb ../lib/cybersource_rest_client/models/payment_products_payer_authentication_configuration_information_card_types_verified_by_visa.rb

mv ../lib/cybersource_rest_client/models/payment_products_payer_authentication_configuration_information_configurations_card_types_verified_by_visa_currencies.rb ../lib/cybersource_rest_client/models/payment_products_payer_authentication_configuration_information_card_types_verified_currencies.rb

mv ../lib/cybersource_rest_client/models/payment_products_secure_acceptance_configuration_information_configurations_notifications_customer_notifications.rb ../lib/cybersource_rest_client/models/payment_product_secure_acceptance_config_customer_notifications.rb

mv ../lib/cybersource_rest_client/models/payment_products_secure_acceptance_configuration_information_configurations_notifications_merchant_notifications.rb ../lib/cybersource_rest_client/models/payment_product_secure_acceptance_config_merchant_notifications.rb

mv ../lib/cybersource_rest_client/models/payment_products_secure_acceptance_configuration_information_configurations_payment_types_card_types.rb ../lib/cybersource_rest_client/models/payment_products_secure_acceptance_config_payment_types_card_types.rb

mv ../lib/cybersource_rest_client/models/payment_products_secure_acceptance_configuration_information_configurations_payment_types_card_types_discover.rb ../lib/cybersource_rest_client/models/payment_products_secure_acceptance_config_payment_types_card_types_discover.rb

mv ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_global_payment_information.rb ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_config_card_not_present_global_payment_info.rb

mv ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_global_payment_information_basic_information.rb ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_config_card_not_present_global_payment_info_basic_info.rb

mv ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_global_payment_information_merchant_defined_data_fields.rb ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_config_card_not_merchant_defined_data_fields.rb

mv ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_global_payment_information_payment_information.rb ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_config_card_not_present_global_payment_info_payment_info.rb

mv ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_receipt_information.rb ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_config_card_not_present_receipt_info.rb

mv ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_receipt_information_email_receipt.rb ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_config_card_not_present_receipt_info_email_receipt.rb

mv ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_receipt_information_header.rb ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_config_card_not_present_receipt_info_header.rb

mv ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_receipt_information_order_information.rb ../lib/cybersource_rest_client/models/payment_products_virtual_terminal_configuration_info_card_not_present_receipt_info_order_info.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_accurint.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_accurint.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_accurint.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_accurint.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_accurint_credentials.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_accurint_credentials.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_credilink.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_credilink.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_credilink_credentials.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_credilink_credentials.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_ekata.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_ekata.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_ekata_credentials.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_ekata_credentials.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_emailage.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_emailage.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_perseuss.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_perseuss.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_signifyd.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_signifyd.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_signifyd_credentials.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_signifyd_credentials.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_targus.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_targus.rb

mv ../lib/cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_targus_credentials.rb ../lib/cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_targus_credentials.rb

sed -i "s|cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_common_merchant_descriptor_information|cybersource_rest_client/models/payment_products_card_processing_configuration_information_merchant_descriptor_information|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_features_card_not_present|cybersource_rest_client/models/payment_products_card_processing_configuration_information_card_not_present|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_features_card_not_present_installment|cybersource_rest_client/models/payment_products_card_processing_configuration_information_card_not_present_installment|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_features_card_not_present_payouts|cybersource_rest_client/models/payment_products_card_processing_configuration_information_card_not_present_payouts|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_features_card_not_present_payouts_currencies|cybersource_rest_client/models/payment_products_card_processing_configuration_information_card_not_present_payouts_currencies|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_features_card_not_present_processors|cybersource_rest_client/models/payment_products_card_processing_configuration_information_card_not_present_processors|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_features_card_present_processors|cybersource_rest_client/models/payment_products_card_processing_configuration_information_card_present_processors|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_card_processing_configuration_information_configurations_features_card_present|cybersource_rest_client/models/payment_products_card_processing_configuration_information_card_present|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_e_check_configuration_information_configurations_features_account_validation_service|cybersource_rest_client/models/payment_products_e_check_configuration_information_account_validation_service|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_e_check_configuration_information_configurations_features_account_validation_service_internal_only|cybersource_rest_client/models/payment_products_e_check_configuration_information_account_validation_service_internal_only|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_e_check_configuration_information_configurations_features_account_validation_service_processors|cybersource_rest_client/models/payment_products_e_check_configuration_information_account_validation_service_processors|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_payer_authentication_configuration_information_configurations_card_types_j_cbj_secure|cybersource_rest_client/models/payment_products_payer_authentication_configuration_information_card_types_j_cbj_secure|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_payer_authentication_configuration_information_configurations_card_types_verified_by_visa|cybersource_rest_client/models/payment_products_payer_authentication_configuration_information_card_types_verified_by_visa|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_payer_authentication_configuration_information_configurations_card_types_verified_by_visa_currencies|cybersource_rest_client/models/payment_products_payer_authentication_configuration_information_card_types_verified_currencies|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_secure_acceptance_configuration_information_configurations_notifications_customer_notifications|cybersource_rest_client/models/payment_product_secure_acceptance_config_customer_notifications|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_secure_acceptance_configuration_information_configurations_notifications_merchant_notifications|cybersource_rest_client/models/payment_product_secure_acceptance_config_merchant_notifications|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_secure_acceptance_configuration_information_configurations_payment_types_card_types|cybersource_rest_client/models/payment_products_secure_acceptance_config_payment_types_card_types|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_secure_acceptance_configuration_information_configurations_payment_types_card_types_discover|cybersource_rest_client/models/payment_products_secure_acceptance_config_payment_types_card_types_discover|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_global_payment_information|cybersource_rest_client/models/payment_products_virtual_terminal_config_card_not_present_global_payment_info|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_global_payment_information_basic_information|cybersource_rest_client/models/payment_products_virtual_terminal_config_card_not_present_global_payment_info_basic_info|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_global_payment_information_merchant_defined_data_fields|cybersource_rest_client/models/payment_products_virtual_terminal_config_card_not_merchant_defined_data_fields|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_global_payment_information_payment_information|cybersource_rest_client/models/payment_products_virtual_terminal_config_card_not_present_global_payment_info_payment_info|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_receipt_information|cybersource_rest_client/models/payment_products_virtual_terminal_config_card_not_present_receipt_info|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_receipt_information_email_receipt|cybersource_rest_client/models/payment_products_virtual_terminal_config_card_not_present_receipt_info_email_receipt|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_receipt_information_header|cybersource_rest_client/models/payment_products_virtual_terminal_config_card_not_present_receipt_info_header|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/payment_products_virtual_terminal_configuration_information_configurations_card_not_present_receipt_information_order_information|cybersource_rest_client/models/payment_products_virtual_terminal_configuration_info_card_not_present_receipt_info_order_info|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty|cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider|cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_accurint|cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_accurint|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_credilink|cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_credilink|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_credilink_credentials|cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_credilink_credentials|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_ekata|cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_ekata|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_ekata_credentials|cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_ekata_credentials|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_emailage|cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_emailage|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_perseuss|cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_perseuss|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_signifyd|cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_signifyd|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_signifyd_credentials|cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_signifyd_credentials|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_targus|cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_targus|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/risk_products_decision_manager_configuration_information_configurations_thirdparty_provider_targus_credentials|cybersource_rest_client/models/risk_products_decision_manager_config_thirdparty_provider_targus_credentials|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/ptsv2payments_processing_information_authorization_options_initiator_merchant_initiated_transaction|cybersource_rest_client/models/ptsv2payments_merchant_initiated_transaction|g" ../lib/cybersource_rest_client.rb

# sed -i "s|cybersource_rest_client/models/risk_v1_authentication_exemptions_post201_response_consumer_authentication_information_strong_authentication|cybersource_rest_client/models/risk_v1_authentication_exemptions_consumer_authentication_information_strong_authentication|g" ../lib/cybersource_rest_client.rb

# sed -i "s|cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response__embedded__embedded_instrument_identifier|cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_embedded_instrument_identifier|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier_processing_information_authorization_options_initiator_merchant_initiated_transaction|cybersource_rest_client/models/tmsv2customers__embedded_merchant_initiated_transaction|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/reporting_v3_interchange_clearing_level_details_get200_response_interchange_clearing_level_details|cybersource_rest_client/models/reporting_get200_response_interchange_clearing_level_details|g" ../lib/cybersource_rest_client.rb

# sed -i "s|cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response__embedded_processing_information_bank_transfer_options|cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response_bank_transfer_options|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier_processing_information_authorization_options_initiator|cybersource_rest_client/models/tmsv2customers__embedded_authorization_options_initiator|g" ../lib/cybersource_rest_client.rb

# sed -i "s|cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response__embedded_buyer_information_personal_identification|cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response_personal_identification|g" ../lib/cybersource_rest_client.rb

# sed -i "s|cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response__embedded_merchant_information_merchant_descriptor|cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response_merchant_descriptor|g" ../lib/cybersource_rest_client.rb

# sed -i "s|cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response__embedded_buyer_information_issued_by|cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response_buyer_information_issued_by|g" ../lib/cybersource_rest_client.rb

# sed -i "s|cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response__embedded_instrument_identifier|cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response_instrument_identifier|g" ../lib/cybersource_rest_client.rb

# sed -i "s|cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response__embedded_merchant_information|cybersource_rest_client/models/tms_v1_instrument_identifiers_payment_instruments_get200_response_merchant_information|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier__links_payment_instruments|cybersource_rest_client/models/tmsv2customers__embedded_payment_instruments|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier_processing_information_authorization_options|cybersource_rest_client/models/tmsv2customers__embedded_authorization_options|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier_processing_information|cybersource_rest_client/models/tmsv2customers__embedded_processing_information|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier_tokenized_card_card|cybersource_rest_client/models/tmsv2customers__embedded_tokenized_card_card|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/pts_v2_payments_post201_response_consumer_authentication_information_strong_authentication_issuer_information|cybersource_rest_client/models/pts_v2_payments_post201_response_consumer_authentication_information_issuer_information|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/tmsv2customers__embedded_default_payment_instrument__embedded_instrument_identifier_tokenized_card|cybersource_rest_client/models/tmsv2customers__embedded_tokenized_card|g" ../lib/cybersource_rest_client.rb

sed -i "s|cybersource_rest_client/models/risk_v1_address_verifications_post201_response_address_verification_information_standard_address_address1|cybersource_rest_client/models/risk_v1_address_verifications_post201_response_address1|g" ../lib/cybersource_rest_client.rb

#sed -i "s|cybersource_rest_client/models/risk_v1_export_compliance_inquiries_post201_response_export_compliance_information_watch_list_matches|cybersource_rest_client/models/risk_v1_export_compliance_inquiries_post201_response_watch_list_matches|g" ../lib/cybersource_rest_client.rb
sed -i 's/$/\r/' ../lib/cybersource_rest_client.rb

#set +v vecho off
#set +v setlocal enableextensions enabledelayedexpansion

#for -f "tokens=1* delims=\" %%A in (
#for files ../lib/AuthenticationSDK/*.rb  "cmd . echo set +v relpath"
# ) do for %%F in (^"%%B) do (
#   export original=%%~F
#   .export removed=%%original:spec=%%
#   if !removed=%%~F (
# #echo NOT PROCESSED
#   ) else (
# if "$testVar = \"!original!\"
# then
# sed -i "s+$fileContents[11]+$fileContents[11]+\"`r`nrequire 'AuthenticationSDK/\"+g;s+\"\\\"+\"/\"+g"; $fileContents ../lib/cybersource_rest_client.rb
#   )
# )

# sed -i "s+require \'\'cybersource_rest_client/api/download_dtd_api\'\'++g;s+require \'\'cybersource_rest_client/api/download_xsd_api\'\'++g" ../lib/cybersource_rest_client.rb"

# to remove beginning / from loc_var_path in all the api files

cd ../lib/cybersource_rest_client/api
for file in ./*.rb; do \
	sed -i "s|local_var_path = "\'"/|local_var_path = "\'"|g" "$file"
	sed -i 's/$/\r/' "$file"
done

cd ../../../

git checkout README.md
git checkout cybersource_rest_client.gemspec

git checkout lib/cybersource_rest_client/api/o_auth_api.rb
git checkout lib/cybersource_rest_client/models/access_token_response.rb
git checkout lib/cybersource_rest_client/models/bad_request_error.rb
git checkout lib/cybersource_rest_client/models/create_access_token_request.rb
git checkout lib/cybersource_rest_client/models/resource_not_found_error.rb
git checkout lib/cybersource_rest_client/models/unauthorized_client_error.rb

git checkout docs/OAuthApi.md
git checkout docs/AccessTokenResponse.md
git checkout docs/BadRequestError.md
git checkout docs/CreateAccessTokenRequest.md
git checkout docs/ResourceNotFoundError.md
git checkout docs/UnauthorizedClientError.md

git checkout spec/api/o_auth_api_spec.rb
git checkout spec/models/access_token_response_spec.rb
git checkout spec/models/bad_request_error_spec.rb
git checkout spec/models/create_access_token_request_spec.rb
git checkout spec/models/resource_not_found_error_spec.rb
git checkout spec/models/unauthorized_client_error_spec.rb

# replace hashValue fieldName to hash for supporting hash field name in request body
cd ./lib/cybersource_rest_client/models
echo "starting of replacing the hash keyword in models"
for file in ./*.rb; do \
    sed -i 's/attr_accessor :sdk_hash_value/attr_accessor :hash \n \t alias :sdk_hash_value :hash/g' "$file"
    sed -i "s/:'sdk_hash_value' => :'sdkHashValue'/:'sdk_hash_value' => :'hash'/g" "$file"
    sed -i "s/:'sdk_hash_value' => :'sdk_hash_value'/:'sdk_hash_value' => :'hash'/g" "$file"
done
echo "completed the task of replacing the hash keyword in models"
