=begin
#CyberSource Merged Spec

#All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.38
=end

require 'spec_helper'
require 'json'

# Unit tests for CyberSource::MerchantDefinedFieldsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MerchantDefinedFieldsApi' do
  before do
    # run before each test
    @instance = CyberSource::MerchantDefinedFieldsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MerchantDefinedFieldsApi' do
    it 'should create an instance of MerchantDefinedFieldsApi' do
      expect(@instance).to be_instance_of(CyberSource::MerchantDefinedFieldsApi)
    end
  end

  # unit tests for create_merchant_defined_field_definition
  # Create merchant defined field for a given reference type
  # @param reference_type The reference type for which merchant defined fields are to be fetched. Available values are Invoice, Purchase, Donation
  # @param merchant_defined_field_definition_request 
  # @param [Hash] opts the optional parameters
  # @return [Array<InlineResponse2002>]
  describe 'create_merchant_defined_field_definition test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_merchant_defined_fields_definitions
  # Get all merchant defined fields for a given reference type
  # @param reference_type The reference type for which merchant defined fields are to be fetched. Available values are Invoice, Purchase, Donation
  # @param [Hash] opts the optional parameters
  # @return [Array<InlineResponse2002>]
  describe 'get_merchant_defined_fields_definitions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoicing_v2_reference_type_merchant_defined_fields_id_delete
  # Delete a MerchantDefinedField by ID
  # @param reference_type 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'invoicing_v2_reference_type_merchant_defined_fields_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoicing_v2_reference_type_merchant_defined_fields_id_put
  # Update a MerchantDefinedField by ID
  # @param reference_type 
  # @param id 
  # @param merchant_defined_field_core 
  # @param [Hash] opts the optional parameters
  # @return [Array<InlineResponse2002>]
  describe 'invoicing_v2_reference_type_merchant_defined_fields_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
