=begin
#CyberSource Merged Spec

#All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.38
=end

require 'spec_helper'
require 'json'

# Unit tests for CyberSource::MerchantRegistrationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MerchantRegistrationApi' do
  before do
    # run before each test
    @instance = CyberSource::MerchantRegistrationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MerchantRegistrationApi' do
    it 'should create an instance of MerchantRegistrationApi' do
      expect(@instance).to be_instance_of(CyberSource::MerchantRegistrationApi)
    end
  end

  # unit tests for activate_merchant_key
  # Activate a merchant key
  # **Activate a Merchant Key**&lt;br&gt;Activates a deactivated encryption key for the specified merchant.&lt;br&gt;&lt;br&gt; **Note:** Expired keys must be renewed via &#x60;PUT /merchants/{merchantId}/keys/{keyId}&#x60; before they can be activated.&lt;br&gt; Returns **403** if the merchant is deactivated or the key is expired, **404** if the merchant or key is not found, **409** if the key is already active. 
  # @param merchant_id Unique merchant identifier (UUID)
  # @param key_id Unique key identifier (UUID)
  # @param [Hash] opts the optional parameters
  # @return [ActivateMerchantKeyResponse200]
  describe 'activate_merchant_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for add_merchant_key
  # Add a key to a merchant
  # **Add a Key to a Merchant**&lt;br&gt;Adds a new encryption key for the specified merchant. The new key is created as ***active*** immediately.&lt;br&gt;&lt;br&gt; **Note:** Adding a new key automatically deactivates all previously active keys for this merchant (single-active key invariant).&lt;br&gt; Returns **403** if the merchant is deactivated, **404** if the merchant is not found. 
  # @param merchant_id Unique merchant identifier (UUID)
  # @param key_request Key creation request
  # @param [Hash] opts the optional parameters
  # @return [ActivateMerchantKeyResponse200]
  describe 'add_merchant_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_merchant
  # Get a merchant
  # **Get a Merchant**&lt;br&gt;Retrieves a single merchant by its unique identifier, including all associated encryption keys.&lt;br&gt;&lt;br&gt; Returns **404** if the merchant is not found. 
  # @param merchant_id Unique merchant identifier (UUID)
  # @param [Hash] opts the optional parameters
  # @return [MerchantRegistrationResponse201]
  describe 'get_merchant test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_merchant_key
  # Get a key by merchant and key ID
  # **Get a Merchant Key**&lt;br&gt;Retrieves a specific encryption key by merchant ID and key ID.&lt;br&gt;&lt;br&gt; Returns **404** if the merchant or key is not found. 
  # @param merchant_id Unique merchant identifier (UUID)
  # @param key_id Unique key identifier (UUID)
  # @param [Hash] opts the optional parameters
  # @return [ActivateMerchantKeyResponse200]
  describe 'get_merchant_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_merchant_keys
  # List keys for a merchant
  # **List Keys for a Merchant**&lt;br&gt;Returns all encryption keys associated with the specified merchant, with optional filtering by key status.&lt;br&gt;&lt;br&gt; Returns **404** if the merchant is not found. 
  # @param merchant_id Unique merchant identifier (UUID)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status Filter by key status: &#39;active&#39;, &#39;deactivated&#39;, or &#39;expired&#39;. Omit to return all keys.
  # @return [ListMerchantKeysResponse200]
  describe 'list_merchant_keys test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for register_merchant
  # Register a merchant
  # **Register a Merchant**&lt;br&gt;Onboards a new merchant into the Visa Merchant Registry Service (VMRS). The merchant declares how payment credentials should be delivered: cryptogram type (TAVV or DAVV), transaction indicator (TAP — Trusted Agent Protocol, ACG — Agentic Checkout Gateway, or BOTH), and whether credentials should be encrypted.&lt;br&gt;&lt;br&gt; If &#x60;paymentPayloadType&#x60; is set to ***ENCRYPTED***, an &#x60;encryptionKey&#x60; must be provided.&lt;br&gt; Returns **409** if a merchant with the same &#x60;merchantUrl&#x60; or &#x60;vmid&#x60; already exists. 
  # @param merchant_request Merchant registration request
  # @param [Hash] opts the optional parameters
  # @return [MerchantRegistrationResponse201]
  describe 'register_merchant test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_merchant
  # Update a merchant
  # **Update a Merchant**&lt;br&gt;Updates merchant configuration. The following fields can be modified: &#x60;merchantName&#x60;, &#x60;merchantUrl&#x60;, &#x60;cryptogramType&#x60;, &#x60;paymentPayloadType&#x60;, &#x60;acceptanceRelationships&#x60;, &#x60;protocolInteractions&#x60;, &#x60;webIntegrations&#x60;, and &#x60;apiIntegrations&#x60;.&lt;br&gt;&lt;br&gt; Partial updates are supported — only provided fields are changed. The &#x60;vmid&#x60; and &#x60;indicator&#x60; fields cannot be updated via this endpoint.&lt;br&gt; Returns **400** if switching to ***ENCRYPTED*** without an active encryption key, **403** if the merchant is deactivated, **404** if not found, **409** if the new &#x60;merchantUrl&#x60; already exists. 
  # @param merchant_id Unique merchant identifier (UUID)
  # @param merchant_update Merchant update request
  # @param [Hash] opts the optional parameters
  # @return [MerchantRegistrationResponse201]
  describe 'update_merchant test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_merchant_key
  # Update a merchant key
  # **Update a Merchant Key**&lt;br&gt;Updates encryption key information. The following fields can be modified: &#x60;keyName&#x60;, &#x60;encryptionKey&#x60;, &#x60;algorithm&#x60;, &#x60;encryptionType&#x60;, and &#x60;expirationDate&#x60;.&lt;br&gt;&lt;br&gt; Returns **403** if the merchant is deactivated, key is deactivated, or key is expired, **404** if the merchant or key is not found, **409** if the new &#x60;keyName&#x60; already exists. 
  # @param merchant_id Unique merchant identifier (UUID)
  # @param key_id Unique key identifier (UUID)
  # @param key_update Key update request
  # @param [Hash] opts the optional parameters
  # @return [ActivateMerchantKeyResponse200]
  describe 'update_merchant_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
