=begin
#CyberSource Merged Spec

#All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.38
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CyberSource::PaymentsProductsCardPresentConnectSubscriptionInformation
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PaymentsProductsCardPresentConnectSubscriptionInformation' do
  before do
    # run before each test
    @instance = CyberSource::PaymentsProductsCardPresentConnectSubscriptionInformation.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentsProductsCardPresentConnectSubscriptionInformation' do
    it 'should create an instance of PaymentsProductsCardPresentConnectSubscriptionInformation' do
      expect(@instance).to be_instance_of(CyberSource::PaymentsProductsCardPresentConnectSubscriptionInformation)
    end
  end
  describe 'test attribute "enabled"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "self_serviceability"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["NOT_SELF_SERVICEABLE"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.self_serviceability = value }.not_to raise_error
      # end
    end
  end

end
