=begin
#CyberSource Merged Spec

#All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.38
=end

require 'date'

module CyberSource
  class PaymentsProductsUnifiedCheckoutSubscriptionInformationFeatures
    attr_accessor :paze_for_unified_checkout

    attr_accessor :token_management

    attr_accessor :pay_pal

    attr_accessor :venmo

    attr_accessor :apple_pay

    attr_accessor :google_pay

    attr_accessor :tink_pay_by_bank

    attr_accessor :e_check

    attr_accessor :p24

    attr_accessor :my_bank

    attr_accessor :konbini

    attr_accessor :dragon_pay

    attr_accessor :decision_manager

    attr_accessor :payer_authentication

    attr_accessor :after_pay

    attr_accessor :ideal

    attr_accessor :multibanco

    attr_accessor :bancontact

    attr_accessor :click_to_pay

    attr_accessor :unified_click_to_pay_sdk

    attr_accessor :portfolio_accessof_sensitive_data

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'paze_for_unified_checkout' => :'pazeForUnifiedCheckout',
        :'token_management' => :'tokenManagement',
        :'pay_pal' => :'payPal',
        :'venmo' => :'venmo',
        :'apple_pay' => :'applePay',
        :'google_pay' => :'googlePay',
        :'tink_pay_by_bank' => :'tinkPayByBank',
        :'e_check' => :'eCheck',
        :'p24' => :'p24',
        :'my_bank' => :'myBank',
        :'konbini' => :'konbini',
        :'dragon_pay' => :'dragonPay',
        :'decision_manager' => :'decisionManager',
        :'payer_authentication' => :'payerAuthentication',
        :'after_pay' => :'afterPay',
        :'ideal' => :'ideal',
        :'multibanco' => :'multibanco',
        :'bancontact' => :'bancontact',
        :'click_to_pay' => :'clickToPay',
        :'unified_click_to_pay_sdk' => :'unifiedClickToPaySDK',
        :'portfolio_accessof_sensitive_data' => :'portfolioAccessofSensitiveData'
      }
    end

    # Attribute mapping from JSON key to ruby-style variable name.
    def self.json_map
      {
        :'paze_for_unified_checkout' => :'paze_for_unified_checkout',
        :'token_management' => :'token_management',
        :'pay_pal' => :'pay_pal',
        :'venmo' => :'venmo',
        :'apple_pay' => :'apple_pay',
        :'google_pay' => :'google_pay',
        :'tink_pay_by_bank' => :'tink_pay_by_bank',
        :'e_check' => :'e_check',
        :'p24' => :'p24',
        :'my_bank' => :'my_bank',
        :'konbini' => :'konbini',
        :'dragon_pay' => :'dragon_pay',
        :'decision_manager' => :'decision_manager',
        :'payer_authentication' => :'payer_authentication',
        :'after_pay' => :'after_pay',
        :'ideal' => :'ideal',
        :'multibanco' => :'multibanco',
        :'bancontact' => :'bancontact',
        :'click_to_pay' => :'click_to_pay',
        :'unified_click_to_pay_sdk' => :'unified_click_to_pay_sdk',
        :'portfolio_accessof_sensitive_data' => :'portfolio_accessof_sensitive_data'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'paze_for_unified_checkout' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesPazeForUnifiedCheckout',
        :'token_management' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesTokenManagement',
        :'pay_pal' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesPayPal',
        :'venmo' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesVenmo',
        :'apple_pay' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesApplePay',
        :'google_pay' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesGooglePay',
        :'tink_pay_by_bank' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesTinkPayByBank',
        :'e_check' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesECheck',
        :'p24' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesP24',
        :'my_bank' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesMyBank',
        :'konbini' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesKonbini',
        :'dragon_pay' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesDragonPay',
        :'decision_manager' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesDecisionManager',
        :'payer_authentication' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesPayerAuthentication',
        :'after_pay' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesAfterPay',
        :'ideal' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesIdeal',
        :'multibanco' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesMultibanco',
        :'bancontact' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesBancontact',
        :'click_to_pay' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesClickToPay',
        :'unified_click_to_pay_sdk' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesUnifiedClickToPaySDK',
        :'portfolio_accessof_sensitive_data' => :'PaymentsProductsUnifiedCheckoutSubscriptionInformationFeaturesPortfolioAccessofSensitiveData'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'pazeForUnifiedCheckout')
        self.paze_for_unified_checkout = attributes[:'pazeForUnifiedCheckout']
      end

      if attributes.has_key?(:'tokenManagement')
        self.token_management = attributes[:'tokenManagement']
      end

      if attributes.has_key?(:'payPal')
        self.pay_pal = attributes[:'payPal']
      end

      if attributes.has_key?(:'venmo')
        self.venmo = attributes[:'venmo']
      end

      if attributes.has_key?(:'applePay')
        self.apple_pay = attributes[:'applePay']
      end

      if attributes.has_key?(:'googlePay')
        self.google_pay = attributes[:'googlePay']
      end

      if attributes.has_key?(:'tinkPayByBank')
        self.tink_pay_by_bank = attributes[:'tinkPayByBank']
      end

      if attributes.has_key?(:'eCheck')
        self.e_check = attributes[:'eCheck']
      end

      if attributes.has_key?(:'p24')
        self.p24 = attributes[:'p24']
      end

      if attributes.has_key?(:'myBank')
        self.my_bank = attributes[:'myBank']
      end

      if attributes.has_key?(:'konbini')
        self.konbini = attributes[:'konbini']
      end

      if attributes.has_key?(:'dragonPay')
        self.dragon_pay = attributes[:'dragonPay']
      end

      if attributes.has_key?(:'decisionManager')
        self.decision_manager = attributes[:'decisionManager']
      end

      if attributes.has_key?(:'payerAuthentication')
        self.payer_authentication = attributes[:'payerAuthentication']
      end

      if attributes.has_key?(:'afterPay')
        self.after_pay = attributes[:'afterPay']
      end

      if attributes.has_key?(:'ideal')
        self.ideal = attributes[:'ideal']
      end

      if attributes.has_key?(:'multibanco')
        self.multibanco = attributes[:'multibanco']
      end

      if attributes.has_key?(:'bancontact')
        self.bancontact = attributes[:'bancontact']
      end

      if attributes.has_key?(:'clickToPay')
        self.click_to_pay = attributes[:'clickToPay']
      end

      if attributes.has_key?(:'unifiedClickToPaySDK')
        self.unified_click_to_pay_sdk = attributes[:'unifiedClickToPaySDK']
      end

      if attributes.has_key?(:'portfolioAccessofSensitiveData')
        self.portfolio_accessof_sensitive_data = attributes[:'portfolioAccessofSensitiveData']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          paze_for_unified_checkout == o.paze_for_unified_checkout &&
          token_management == o.token_management &&
          pay_pal == o.pay_pal &&
          venmo == o.venmo &&
          apple_pay == o.apple_pay &&
          google_pay == o.google_pay &&
          tink_pay_by_bank == o.tink_pay_by_bank &&
          e_check == o.e_check &&
          p24 == o.p24 &&
          my_bank == o.my_bank &&
          konbini == o.konbini &&
          dragon_pay == o.dragon_pay &&
          decision_manager == o.decision_manager &&
          payer_authentication == o.payer_authentication &&
          after_pay == o.after_pay &&
          ideal == o.ideal &&
          multibanco == o.multibanco &&
          bancontact == o.bancontact &&
          click_to_pay == o.click_to_pay &&
          unified_click_to_pay_sdk == o.unified_click_to_pay_sdk &&
          portfolio_accessof_sensitive_data == o.portfolio_accessof_sensitive_data
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [paze_for_unified_checkout, token_management, pay_pal, venmo, apple_pay, google_pay, tink_pay_by_bank, e_check, p24, my_bank, konbini, dragon_pay, decision_manager, payer_authentication, after_pay, ideal, multibanco, bancontact, click_to_pay, unified_click_to_pay_sdk, portfolio_accessof_sensitive_data].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{self.class.json_map[key]}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{self.class.json_map[key]}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CyberSource.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
