=begin
#CyberSource Merged Spec

#All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.38
=end

require 'date'

module CyberSource
  class Ptsv1pullfundstransferSenderInformation
    # Sender's postal code. This field is conditional: it is required if using neither a Customer nor Payment Instrument token. 
    attr_accessor :postal_code

    # First name of sender. This field is conditional: it is required if using neither a Customer nor Payment Instrument token. 
    attr_accessor :first_name

    # Middle Initial of sender 
    attr_accessor :middle_initial

    # This field contains the middle name of the entity funding the transaction. 
    attr_accessor :middle_name

    # Last name of sender. This field is conditional: it is required if using neither a Customer nor Payment Instrument token. 
    attr_accessor :last_name

    # Street address of sender. This field is conditional: it is required if using neither a Customer nor Payment Instrument token. 
    attr_accessor :address1

    # Second line of the sender's address. 
    attr_accessor :address2

    # City of sender. This field is conditional: it is required if using neither a Customer nor Payment Instrument token. 
    attr_accessor :locality

    # Sender's state. Use the **State, Province, and Territory Codes for the United States and Canada**. This field is conditional: it is required if in the United States or Canada, and transaction is using neither a Customer nor Payment Instrument token.   Value must be an ISO Standard State Code: [https://developer.cybersource.com/library/documentation/sbc/quickref/states_and_provinces.pdf](https://developer.cybersource.com/library/documentation/sbc/quickref/states_and_provinces.pdf) 
    attr_accessor :administrative_area

    # Country of sender. Check that this field contains 2 character alpha ISO 3166-1 standard values. This field is conditional: it is required if using neither a Customer nor Payment Instrument token. 
    attr_accessor :country

    attr_accessor :payment_information

    attr_accessor :consumer_authentication

    attr_accessor :personal_identification

    # Visa Direct(16 characters)   If the transaction is a money transfer, pre-paid load, or credit card bill pay, and if the sender intends to fund the transaction with a non-financial instrument (for example, cash), a reference number unique to the sender is required.   If the transaction is a funds disbursement, the field is required. 
    attr_accessor :reference_number

    attr_accessor :account

    # Sender's alias name. 
    attr_accessor :alias_name

    # Account Owner Country of Birth. 
    attr_accessor :country_of_birth

    # Sender's date of birth. Format: YYYYMMDD. 
    attr_accessor :date_of_birth

    # Account Owner email address 
    attr_accessor :email

    # Name of sender. Use this field if the sender is a business. 
    attr_accessor :name

    # Account Owner Nationality 
    attr_accessor :nationality

    # Account Owner Occupation. 
    attr_accessor :occupation

    # Sender's phone number. 
    attr_accessor :phone_number

    # This field identifies if the sender is a business or an individual.   The valid values are:   • `B` (Business)   • `I` (Individual) 
    attr_accessor :type

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'postal_code' => :'postalCode',
        :'first_name' => :'firstName',
        :'middle_initial' => :'middleInitial',
        :'middle_name' => :'middleName',
        :'last_name' => :'lastName',
        :'address1' => :'address1',
        :'address2' => :'address2',
        :'locality' => :'locality',
        :'administrative_area' => :'administrativeArea',
        :'country' => :'country',
        :'payment_information' => :'paymentInformation',
        :'consumer_authentication' => :'consumerAuthentication',
        :'personal_identification' => :'personalIdentification',
        :'reference_number' => :'referenceNumber',
        :'account' => :'account',
        :'alias_name' => :'aliasName',
        :'country_of_birth' => :'countryOfBirth',
        :'date_of_birth' => :'dateOfBirth',
        :'email' => :'email',
        :'name' => :'name',
        :'nationality' => :'nationality',
        :'occupation' => :'occupation',
        :'phone_number' => :'phoneNumber',
        :'type' => :'type'
      }
    end

    # Attribute mapping from JSON key to ruby-style variable name.
    def self.json_map
      {
        :'postal_code' => :'postal_code',
        :'first_name' => :'first_name',
        :'middle_initial' => :'middle_initial',
        :'middle_name' => :'middle_name',
        :'last_name' => :'last_name',
        :'address1' => :'address1',
        :'address2' => :'address2',
        :'locality' => :'locality',
        :'administrative_area' => :'administrative_area',
        :'country' => :'country',
        :'payment_information' => :'payment_information',
        :'consumer_authentication' => :'consumer_authentication',
        :'personal_identification' => :'personal_identification',
        :'reference_number' => :'reference_number',
        :'account' => :'account',
        :'alias_name' => :'alias_name',
        :'country_of_birth' => :'country_of_birth',
        :'date_of_birth' => :'date_of_birth',
        :'email' => :'email',
        :'name' => :'name',
        :'nationality' => :'nationality',
        :'occupation' => :'occupation',
        :'phone_number' => :'phone_number',
        :'type' => :'type'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'postal_code' => :'String',
        :'first_name' => :'String',
        :'middle_initial' => :'String',
        :'middle_name' => :'String',
        :'last_name' => :'String',
        :'address1' => :'String',
        :'address2' => :'String',
        :'locality' => :'String',
        :'administrative_area' => :'String',
        :'country' => :'String',
        :'payment_information' => :'Ptsv1pullfundstransferSenderInformationPaymentInformation',
        :'consumer_authentication' => :'Ptsv1pullfundstransferSenderInformationConsumerAuthentication',
        :'personal_identification' => :'Ptsv1pullfundstransferSenderInformationPersonalIdentification',
        :'reference_number' => :'String',
        :'account' => :'Ptsv1pullfundstransferSenderInformationAccount',
        :'alias_name' => :'String',
        :'country_of_birth' => :'String',
        :'date_of_birth' => :'String',
        :'email' => :'String',
        :'name' => :'String',
        :'nationality' => :'String',
        :'occupation' => :'String',
        :'phone_number' => :'String',
        :'type' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'postalCode')
        self.postal_code = attributes[:'postalCode']
      end

      if attributes.has_key?(:'firstName')
        self.first_name = attributes[:'firstName']
      end

      if attributes.has_key?(:'middleInitial')
        self.middle_initial = attributes[:'middleInitial']
      end

      if attributes.has_key?(:'middleName')
        self.middle_name = attributes[:'middleName']
      end

      if attributes.has_key?(:'lastName')
        self.last_name = attributes[:'lastName']
      end

      if attributes.has_key?(:'address1')
        self.address1 = attributes[:'address1']
      end

      if attributes.has_key?(:'address2')
        self.address2 = attributes[:'address2']
      end

      if attributes.has_key?(:'locality')
        self.locality = attributes[:'locality']
      end

      if attributes.has_key?(:'administrativeArea')
        self.administrative_area = attributes[:'administrativeArea']
      end

      if attributes.has_key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.has_key?(:'paymentInformation')
        self.payment_information = attributes[:'paymentInformation']
      end

      if attributes.has_key?(:'consumerAuthentication')
        self.consumer_authentication = attributes[:'consumerAuthentication']
      end

      if attributes.has_key?(:'personalIdentification')
        self.personal_identification = attributes[:'personalIdentification']
      end

      if attributes.has_key?(:'referenceNumber')
        self.reference_number = attributes[:'referenceNumber']
      end

      if attributes.has_key?(:'account')
        self.account = attributes[:'account']
      end

      if attributes.has_key?(:'aliasName')
        self.alias_name = attributes[:'aliasName']
      end

      if attributes.has_key?(:'countryOfBirth')
        self.country_of_birth = attributes[:'countryOfBirth']
      end

      if attributes.has_key?(:'dateOfBirth')
        self.date_of_birth = attributes[:'dateOfBirth']
      end

      if attributes.has_key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'nationality')
        self.nationality = attributes[:'nationality']
      end

      if attributes.has_key?(:'occupation')
        self.occupation = attributes[:'occupation']
      end

      if attributes.has_key?(:'phoneNumber')
        self.phone_number = attributes[:'phoneNumber']
      end

      if attributes.has_key?(:'type')
        self.type = attributes[:'type']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      #if !@country.nil? && @country !~ Regexp.new(/^(\\s{0,2}|.{2})$/)
        #invalid_properties.push('invalid value for "country", must conform to the pattern /^(\\s{0,2}|.{2})$/.')
      #end

      #if !@country_of_birth.nil? && @country_of_birth !~ Regexp.new(/^(\\s{0,2}|.{2})$/)
        #invalid_properties.push('invalid value for "country_of_birth", must conform to the pattern /^(\\s{0,2}|.{2})$/.')
      #end

      #if !@nationality.nil? && @nationality !~ Regexp.new(/^(\\s{0,2}|.{2})$/)
        #invalid_properties.push('invalid value for "nationality", must conform to the pattern /^(\\s{0,2}|.{2})$/.')
      #end

      #if !@type.nil? && @type !~ Regexp.new(/^(\\s{0,1}|.{1})$/)
        #invalid_properties.push('invalid value for "type", must conform to the pattern /^(\\s{0,1}|.{1})$/.')
      #end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      #return false if !@country.nil? && @country !~ Regexp.new(/^(\\s{0,2}|.{2})$/)
      #return false if !@country_of_birth.nil? && @country_of_birth !~ Regexp.new(/^(\\s{0,2}|.{2})$/)
      #return false if !@nationality.nil? && @nationality !~ Regexp.new(/^(\\s{0,2}|.{2})$/)
      #return false if !@type.nil? && @type !~ Regexp.new(/^(\\s{0,1}|.{1})$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] postal_code Value to be assigned
    def postal_code=(postal_code)
      @postal_code = postal_code
    end

    # Custom attribute writer method with validation
    # @param [Object] first_name Value to be assigned
    def first_name=(first_name)
      @first_name = first_name
    end

    # Custom attribute writer method with validation
    # @param [Object] middle_initial Value to be assigned
    def middle_initial=(middle_initial)
      @middle_initial = middle_initial
    end

    # Custom attribute writer method with validation
    # @param [Object] middle_name Value to be assigned
    def middle_name=(middle_name)
      @middle_name = middle_name
    end

    # Custom attribute writer method with validation
    # @param [Object] last_name Value to be assigned
    def last_name=(last_name)
      @last_name = last_name
    end

    # Custom attribute writer method with validation
    # @param [Object] address1 Value to be assigned
    def address1=(address1)
      @address1 = address1
    end

    # Custom attribute writer method with validation
    # @param [Object] address2 Value to be assigned
    def address2=(address2)
      @address2 = address2
    end

    # Custom attribute writer method with validation
    # @param [Object] locality Value to be assigned
    def locality=(locality)
      @locality = locality
    end

    # Custom attribute writer method with validation
    # @param [Object] administrative_area Value to be assigned
    def administrative_area=(administrative_area)
      @administrative_area = administrative_area
    end

    # Custom attribute writer method with validation
    # @param [Object] country Value to be assigned
    def country=(country)
      #if !country.nil? && country !~ Regexp.new(/^(\\s{0,2}|.{2})$/)
        #fail ArgumentError, 'invalid value for "country", must conform to the pattern /^(\\s{0,2}|.{2})$/.'
      #end

      @country = country
    end

    # Custom attribute writer method with validation
    # @param [Object] reference_number Value to be assigned
    def reference_number=(reference_number)
      @reference_number = reference_number
    end

    # Custom attribute writer method with validation
    # @param [Object] alias_name Value to be assigned
    def alias_name=(alias_name)
      @alias_name = alias_name
    end

    # Custom attribute writer method with validation
    # @param [Object] country_of_birth Value to be assigned
    def country_of_birth=(country_of_birth)
      #if !country_of_birth.nil? && country_of_birth !~ Regexp.new(/^(\\s{0,2}|.{2})$/)
        #fail ArgumentError, 'invalid value for "country_of_birth", must conform to the pattern /^(\\s{0,2}|.{2})$/.'
      #end

      @country_of_birth = country_of_birth
    end

    # Custom attribute writer method with validation
    # @param [Object] date_of_birth Value to be assigned
    def date_of_birth=(date_of_birth)
      @date_of_birth = date_of_birth
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      @email = email
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] nationality Value to be assigned
    def nationality=(nationality)
      #if !nationality.nil? && nationality !~ Regexp.new(/^(\\s{0,2}|.{2})$/)
        #fail ArgumentError, 'invalid value for "nationality", must conform to the pattern /^(\\s{0,2}|.{2})$/.'
      #end

      @nationality = nationality
    end

    # Custom attribute writer method with validation
    # @param [Object] occupation Value to be assigned
    def occupation=(occupation)
      @occupation = occupation
    end

    # Custom attribute writer method with validation
    # @param [Object] phone_number Value to be assigned
    def phone_number=(phone_number)
      @phone_number = phone_number
    end

    # Custom attribute writer method with validation
    # @param [Object] type Value to be assigned
    def type=(type)
      #if !type.nil? && type !~ Regexp.new(/^(\\s{0,1}|.{1})$/)
        #fail ArgumentError, 'invalid value for "type", must conform to the pattern /^(\\s{0,1}|.{1})$/.'
      #end

      @type = type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          postal_code == o.postal_code &&
          first_name == o.first_name &&
          middle_initial == o.middle_initial &&
          middle_name == o.middle_name &&
          last_name == o.last_name &&
          address1 == o.address1 &&
          address2 == o.address2 &&
          locality == o.locality &&
          administrative_area == o.administrative_area &&
          country == o.country &&
          payment_information == o.payment_information &&
          consumer_authentication == o.consumer_authentication &&
          personal_identification == o.personal_identification &&
          reference_number == o.reference_number &&
          account == o.account &&
          alias_name == o.alias_name &&
          country_of_birth == o.country_of_birth &&
          date_of_birth == o.date_of_birth &&
          email == o.email &&
          name == o.name &&
          nationality == o.nationality &&
          occupation == o.occupation &&
          phone_number == o.phone_number &&
          type == o.type
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [postal_code, first_name, middle_initial, middle_name, last_name, address1, address2, locality, administrative_area, country, payment_information, consumer_authentication, personal_identification, reference_number, account, alias_name, country_of_birth, date_of_birth, email, name, nationality, occupation, phone_number, type].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{self.class.json_map[key]}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{self.class.json_map[key]}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CyberSource.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
