=begin
#CyberSource Merged Spec

#All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.38
=end

require 'date'

module CyberSource
  class TssV2TransactionsGet200Response
    # An unique identification number generated by Cybersource to identify the submitted request. Returned by all services. It is also appended to the endpoint of the resource. On incremental authorizations, this value with be the same as the identification number returned in the original authorization response. 
    attr_accessor :id

    # Contains the transaction identifier for the first transaction in the series of transactions. For example, you might send an authorization request for a payment, followed by a capture request for that payment, and then a refund request for that captured payment. Each of those requests, if successful, creates a resource that is assigned an identifier, which is returned in the response. The rootId identifies the first ID in the series, which in this case would be the ID of the original authorization.
    attr_accessor :root_id

    # Reference number for the transaction. Depending on how your Cybersource account is configured, this value could either be provided in the API request or generated by CyberSource. The actual value used in the request to the processor is provided back to you by Cybersource in the response. 
    attr_accessor :reconciliation_id

    # Your CyberSource merchant ID.
    attr_accessor :merchant_id

    # Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ` **Example** `2016-08-11T22:47:57Z` equals August 11, 2016, at 22:47:57 (10:47:57 p.m.). The `T` separates the date and the time. The `Z` indicates UTC.  Returned by Cybersource for all services. 
    attr_accessor :submit_time_utc

    # The status of the submitted transaction.
    attr_accessor :status

    attr_accessor :application_information

    attr_accessor :buyer_information

    attr_accessor :client_reference_information

    attr_accessor :consumer_authentication_information

    attr_accessor :device_information

    attr_accessor :error_information

    attr_accessor :installment_information

    attr_accessor :fraud_marking_information

    attr_accessor :health_care_information

    # The object containing the custom data that the merchant defines. 
    attr_accessor :merchant_defined_information

    attr_accessor :merchant_information

    attr_accessor :order_information

    attr_accessor :payment_information

    attr_accessor :payment_insights_information

    attr_accessor :payout_options

    attr_accessor :unscheduled_payment_information

    attr_accessor :processing_information

    attr_accessor :processor_information

    attr_accessor :recurring_payment_information

    attr_accessor :point_of_sale_information

    attr_accessor :risk_information

    attr_accessor :sender_information

    attr_accessor :token_information

    attr_accessor :_links

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'root_id' => :'rootId',
        :'reconciliation_id' => :'reconciliationId',
        :'merchant_id' => :'merchantId',
        :'submit_time_utc' => :'submitTimeUTC',
        :'status' => :'status',
        :'application_information' => :'applicationInformation',
        :'buyer_information' => :'buyerInformation',
        :'client_reference_information' => :'clientReferenceInformation',
        :'consumer_authentication_information' => :'consumerAuthenticationInformation',
        :'device_information' => :'deviceInformation',
        :'error_information' => :'errorInformation',
        :'installment_information' => :'installmentInformation',
        :'fraud_marking_information' => :'fraudMarkingInformation',
        :'health_care_information' => :'healthCareInformation',
        :'merchant_defined_information' => :'merchantDefinedInformation',
        :'merchant_information' => :'merchantInformation',
        :'order_information' => :'orderInformation',
        :'payment_information' => :'paymentInformation',
        :'payment_insights_information' => :'paymentInsightsInformation',
        :'payout_options' => :'payoutOptions',
        :'unscheduled_payment_information' => :'unscheduledPaymentInformation',
        :'processing_information' => :'processingInformation',
        :'processor_information' => :'processorInformation',
        :'recurring_payment_information' => :'recurringPaymentInformation',
        :'point_of_sale_information' => :'pointOfSaleInformation',
        :'risk_information' => :'riskInformation',
        :'sender_information' => :'senderInformation',
        :'token_information' => :'tokenInformation',
        :'_links' => :'_links'
      }
    end

    # Attribute mapping from JSON key to ruby-style variable name.
    def self.json_map
      {
        :'id' => :'id',
        :'root_id' => :'root_id',
        :'reconciliation_id' => :'reconciliation_id',
        :'merchant_id' => :'merchant_id',
        :'submit_time_utc' => :'submit_time_utc',
        :'status' => :'status',
        :'application_information' => :'application_information',
        :'buyer_information' => :'buyer_information',
        :'client_reference_information' => :'client_reference_information',
        :'consumer_authentication_information' => :'consumer_authentication_information',
        :'device_information' => :'device_information',
        :'error_information' => :'error_information',
        :'installment_information' => :'installment_information',
        :'fraud_marking_information' => :'fraud_marking_information',
        :'health_care_information' => :'health_care_information',
        :'merchant_defined_information' => :'merchant_defined_information',
        :'merchant_information' => :'merchant_information',
        :'order_information' => :'order_information',
        :'payment_information' => :'payment_information',
        :'payment_insights_information' => :'payment_insights_information',
        :'payout_options' => :'payout_options',
        :'unscheduled_payment_information' => :'unscheduled_payment_information',
        :'processing_information' => :'processing_information',
        :'processor_information' => :'processor_information',
        :'recurring_payment_information' => :'recurring_payment_information',
        :'point_of_sale_information' => :'point_of_sale_information',
        :'risk_information' => :'risk_information',
        :'sender_information' => :'sender_information',
        :'token_information' => :'token_information',
        :'_links' => :'_links'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'String',
        :'root_id' => :'String',
        :'reconciliation_id' => :'String',
        :'merchant_id' => :'String',
        :'submit_time_utc' => :'String',
        :'status' => :'String',
        :'application_information' => :'TssV2TransactionsGet200ResponseApplicationInformation',
        :'buyer_information' => :'TssV2TransactionsGet200ResponseBuyerInformation',
        :'client_reference_information' => :'TssV2TransactionsGet200ResponseClientReferenceInformation',
        :'consumer_authentication_information' => :'TssV2TransactionsGet200ResponseConsumerAuthenticationInformation',
        :'device_information' => :'TssV2TransactionsGet200ResponseDeviceInformation',
        :'error_information' => :'TssV2TransactionsGet200ResponseErrorInformation',
        :'installment_information' => :'TssV2TransactionsGet200ResponseInstallmentInformation',
        :'fraud_marking_information' => :'TssV2TransactionsGet200ResponseFraudMarkingInformation',
        :'health_care_information' => :'Ptsv2paymentsHealthCareInformation',
        :'merchant_defined_information' => :'Array<Ptsv2paymentsMerchantDefinedInformation>',
        :'merchant_information' => :'TssV2TransactionsGet200ResponseMerchantInformation',
        :'order_information' => :'TssV2TransactionsGet200ResponseOrderInformation',
        :'payment_information' => :'TssV2TransactionsGet200ResponsePaymentInformation',
        :'payment_insights_information' => :'PtsV2PaymentsPost201ResponsePaymentInsightsInformation',
        :'payout_options' => :'TssV2TransactionsGet200ResponsePayoutOptions',
        :'unscheduled_payment_information' => :'TssV2TransactionsGet200ResponseUnscheduledPaymentInformation',
        :'processing_information' => :'TssV2TransactionsGet200ResponseProcessingInformation',
        :'processor_information' => :'TssV2TransactionsGet200ResponseProcessorInformation',
        :'recurring_payment_information' => :'TssV2TransactionsGet200ResponseRecurringPaymentInformation',
        :'point_of_sale_information' => :'TssV2TransactionsGet200ResponsePointOfSaleInformation',
        :'risk_information' => :'TssV2TransactionsGet200ResponseRiskInformation',
        :'sender_information' => :'TssV2TransactionsGet200ResponseSenderInformation',
        :'token_information' => :'TssV2TransactionsGet200ResponseTokenInformation',
        :'_links' => :'TssV2TransactionsGet200ResponseLinks'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'rootId')
        self.root_id = attributes[:'rootId']
      end

      if attributes.has_key?(:'reconciliationId')
        self.reconciliation_id = attributes[:'reconciliationId']
      end

      if attributes.has_key?(:'merchantId')
        self.merchant_id = attributes[:'merchantId']
      end

      if attributes.has_key?(:'submitTimeUTC')
        self.submit_time_utc = attributes[:'submitTimeUTC']
      end

      if attributes.has_key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.has_key?(:'applicationInformation')
        self.application_information = attributes[:'applicationInformation']
      end

      if attributes.has_key?(:'buyerInformation')
        self.buyer_information = attributes[:'buyerInformation']
      end

      if attributes.has_key?(:'clientReferenceInformation')
        self.client_reference_information = attributes[:'clientReferenceInformation']
      end

      if attributes.has_key?(:'consumerAuthenticationInformation')
        self.consumer_authentication_information = attributes[:'consumerAuthenticationInformation']
      end

      if attributes.has_key?(:'deviceInformation')
        self.device_information = attributes[:'deviceInformation']
      end

      if attributes.has_key?(:'errorInformation')
        self.error_information = attributes[:'errorInformation']
      end

      if attributes.has_key?(:'installmentInformation')
        self.installment_information = attributes[:'installmentInformation']
      end

      if attributes.has_key?(:'fraudMarkingInformation')
        self.fraud_marking_information = attributes[:'fraudMarkingInformation']
      end

      if attributes.has_key?(:'healthCareInformation')
        self.health_care_information = attributes[:'healthCareInformation']
      end

      if attributes.has_key?(:'merchantDefinedInformation')
        if (value = attributes[:'merchantDefinedInformation']).is_a?(Array)
          self.merchant_defined_information = value
        end
      end

      if attributes.has_key?(:'merchantInformation')
        self.merchant_information = attributes[:'merchantInformation']
      end

      if attributes.has_key?(:'orderInformation')
        self.order_information = attributes[:'orderInformation']
      end

      if attributes.has_key?(:'paymentInformation')
        self.payment_information = attributes[:'paymentInformation']
      end

      if attributes.has_key?(:'paymentInsightsInformation')
        self.payment_insights_information = attributes[:'paymentInsightsInformation']
      end

      if attributes.has_key?(:'payoutOptions')
        self.payout_options = attributes[:'payoutOptions']
      end

      if attributes.has_key?(:'unscheduledPaymentInformation')
        self.unscheduled_payment_information = attributes[:'unscheduledPaymentInformation']
      end

      if attributes.has_key?(:'processingInformation')
        self.processing_information = attributes[:'processingInformation']
      end

      if attributes.has_key?(:'processorInformation')
        self.processor_information = attributes[:'processorInformation']
      end

      if attributes.has_key?(:'recurringPaymentInformation')
        self.recurring_payment_information = attributes[:'recurringPaymentInformation']
      end

      if attributes.has_key?(:'pointOfSaleInformation')
        self.point_of_sale_information = attributes[:'pointOfSaleInformation']
      end

      if attributes.has_key?(:'riskInformation')
        self.risk_information = attributes[:'riskInformation']
      end

      if attributes.has_key?(:'senderInformation')
        self.sender_information = attributes[:'senderInformation']
      end

      if attributes.has_key?(:'tokenInformation')
        self.token_information = attributes[:'tokenInformation']
      end

      if attributes.has_key?(:'_links')
        self._links = attributes[:'_links']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] root_id Value to be assigned
    def root_id=(root_id)
      @root_id = root_id
    end

    # Custom attribute writer method with validation
    # @param [Object] reconciliation_id Value to be assigned
    def reconciliation_id=(reconciliation_id)
      @reconciliation_id = reconciliation_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          root_id == o.root_id &&
          reconciliation_id == o.reconciliation_id &&
          merchant_id == o.merchant_id &&
          submit_time_utc == o.submit_time_utc &&
          status == o.status &&
          application_information == o.application_information &&
          buyer_information == o.buyer_information &&
          client_reference_information == o.client_reference_information &&
          consumer_authentication_information == o.consumer_authentication_information &&
          device_information == o.device_information &&
          error_information == o.error_information &&
          installment_information == o.installment_information &&
          fraud_marking_information == o.fraud_marking_information &&
          health_care_information == o.health_care_information &&
          merchant_defined_information == o.merchant_defined_information &&
          merchant_information == o.merchant_information &&
          order_information == o.order_information &&
          payment_information == o.payment_information &&
          payment_insights_information == o.payment_insights_information &&
          payout_options == o.payout_options &&
          unscheduled_payment_information == o.unscheduled_payment_information &&
          processing_information == o.processing_information &&
          processor_information == o.processor_information &&
          recurring_payment_information == o.recurring_payment_information &&
          point_of_sale_information == o.point_of_sale_information &&
          risk_information == o.risk_information &&
          sender_information == o.sender_information &&
          token_information == o.token_information &&
          _links == o._links
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, root_id, reconciliation_id, merchant_id, submit_time_utc, status, application_information, buyer_information, client_reference_information, consumer_authentication_information, device_information, error_information, installment_information, fraud_marking_information, health_care_information, merchant_defined_information, merchant_information, order_information, payment_information, payment_insights_information, payout_options, unscheduled_payment_information, processing_information, processor_information, recurring_payment_information, point_of_sale_information, risk_information, sender_information, token_information, _links].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{self.class.json_map[key]}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{self.class.json_map[key]}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CyberSource.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
