=begin
#CyberSource Merged Spec

#All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.38
=end

require 'date'

module CyberSource
  class UnifiedriskAuthentication
    # Unique identifier assigned to an authentication attempt
    attr_accessor :authentication_id

    # Authentication method used during the authentication/MFA process
    attr_accessor :method

    # Whether multi-factor authentication was completed successfully
    attr_accessor :mfa_successful

    # Phone number used for authentication (e.g., SMS/voice MFA)
    attr_accessor :phone_number

    # Email address used for authentication (e.g., verification code delivery)
    attr_accessor :email

    # Additional authentication-related information not captured by other fields
    attr_accessor :other

    # Unique identifier assigned to the 3D Secure requestor (typically the merchant or payment service provider) by the directory server for authentication routing
    attr_accessor :three_ds_requestor_id

    # The business or brand name of the 3D Secure requestor as registered with the card network directory server
    attr_accessor :three_ds_requestor_name

    attr_accessor :challenge

    # Indicates whether decoupled authentication is requested or supported, allowing the cardholder to authenticate outside the main transaction flow. Values - \"Y\" (supported and preferred), \"N\" (do not use)
    attr_accessor :decoupled_indicator

    # Maximum time in minutes allowed for the cardholder to complete a decoupled authentication, after which the session expires
    attr_accessor :decoupled_max_time

    # Indicates the reason for the 3DS Requestor Initiated (3RI) transaction - a merchant-initiated authentication without active cardholder participation. Values defined by EMVCo 3DS specification
    attr_accessor :three_ri_indicator

    # Indicates the type of authentication request being made, such as payment authentication, non-payment authentication, or recurring/installment transactions
    attr_accessor :authentication_indicator

    # The date and time when the cardholder completed authentication, used for tracking authentication timing and fraud analysis
    attr_accessor :authentication_date

    # The cardholder's preferred language for the authentication challenge interface, expressed as an IETF BCP 47 language tag (e.g., en-US, fr-FR)
    attr_accessor :language_preference

    # Indicates whether the merchant's environment supports the Secure Payment Confirmation (SPC) protocol for frictionless authentication using FIDO2/WebAuthn credentials
    attr_accessor :spc_support

    # Indicates the reason why an SPC (Secure Payment Confirmation) transaction was not completed, helping distinguish cardholder-initiated abandonment from technical failures
    attr_accessor :spc_incomplete_indicator

    # The 3D Secure protocol version used for this authentication attempt (e.g., \"2.1.0\", \"2.2.0\"), which determines which fields and features are supported
    attr_accessor :version

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'authentication_id' => :'authenticationId',
        :'method' => :'method',
        :'mfa_successful' => :'mfaSuccessful',
        :'phone_number' => :'phoneNumber',
        :'email' => :'email',
        :'other' => :'other',
        :'three_ds_requestor_id' => :'threeDSRequestorId',
        :'three_ds_requestor_name' => :'threeDSRequestorName',
        :'challenge' => :'challenge',
        :'decoupled_indicator' => :'decoupledIndicator',
        :'decoupled_max_time' => :'decoupledMaxTime',
        :'three_ri_indicator' => :'threeRIIndicator',
        :'authentication_indicator' => :'authenticationIndicator',
        :'authentication_date' => :'authenticationDate',
        :'language_preference' => :'languagePreference',
        :'spc_support' => :'spcSupport',
        :'spc_incomplete_indicator' => :'spcIncompleteIndicator',
        :'version' => :'version'
      }
    end

    # Attribute mapping from JSON key to ruby-style variable name.
    def self.json_map
      {
        :'authentication_id' => :'authentication_id',
        :'method' => :'method',
        :'mfa_successful' => :'mfa_successful',
        :'phone_number' => :'phone_number',
        :'email' => :'email',
        :'other' => :'other',
        :'three_ds_requestor_id' => :'three_ds_requestor_id',
        :'three_ds_requestor_name' => :'three_ds_requestor_name',
        :'challenge' => :'challenge',
        :'decoupled_indicator' => :'decoupled_indicator',
        :'decoupled_max_time' => :'decoupled_max_time',
        :'three_ri_indicator' => :'three_ri_indicator',
        :'authentication_indicator' => :'authentication_indicator',
        :'authentication_date' => :'authentication_date',
        :'language_preference' => :'language_preference',
        :'spc_support' => :'spc_support',
        :'spc_incomplete_indicator' => :'spc_incomplete_indicator',
        :'version' => :'version'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'authentication_id' => :'String',
        :'method' => :'String',
        :'mfa_successful' => :'BOOLEAN',
        :'phone_number' => :'String',
        :'email' => :'String',
        :'other' => :'String',
        :'three_ds_requestor_id' => :'String',
        :'three_ds_requestor_name' => :'String',
        :'challenge' => :'UnifiedriskAuthenticationChallenge',
        :'decoupled_indicator' => :'String',
        :'decoupled_max_time' => :'String',
        :'three_ri_indicator' => :'String',
        :'authentication_indicator' => :'String',
        :'authentication_date' => :'String',
        :'language_preference' => :'Array<String>',
        :'spc_support' => :'String',
        :'spc_incomplete_indicator' => :'String',
        :'version' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'authenticationId')
        self.authentication_id = attributes[:'authenticationId']
      end

      if attributes.has_key?(:'method')
        self.method = attributes[:'method']
      end

      if attributes.has_key?(:'mfaSuccessful')
        self.mfa_successful = attributes[:'mfaSuccessful']
      end

      if attributes.has_key?(:'phoneNumber')
        self.phone_number = attributes[:'phoneNumber']
      end

      if attributes.has_key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.has_key?(:'other')
        self.other = attributes[:'other']
      end

      if attributes.has_key?(:'threeDSRequestorId')
        self.three_ds_requestor_id = attributes[:'threeDSRequestorId']
      end

      if attributes.has_key?(:'threeDSRequestorName')
        self.three_ds_requestor_name = attributes[:'threeDSRequestorName']
      end

      if attributes.has_key?(:'challenge')
        self.challenge = attributes[:'challenge']
      end

      if attributes.has_key?(:'decoupledIndicator')
        self.decoupled_indicator = attributes[:'decoupledIndicator']
      end

      if attributes.has_key?(:'decoupledMaxTime')
        self.decoupled_max_time = attributes[:'decoupledMaxTime']
      end

      if attributes.has_key?(:'threeRIIndicator')
        self.three_ri_indicator = attributes[:'threeRIIndicator']
      end

      if attributes.has_key?(:'authenticationIndicator')
        self.authentication_indicator = attributes[:'authenticationIndicator']
      end

      if attributes.has_key?(:'authenticationDate')
        self.authentication_date = attributes[:'authenticationDate']
      end

      if attributes.has_key?(:'languagePreference')
        if (value = attributes[:'languagePreference']).is_a?(Array)
          self.language_preference = value
        end
      end

      if attributes.has_key?(:'spcSupport')
        self.spc_support = attributes[:'spcSupport']
      end

      if attributes.has_key?(:'spcIncompleteIndicator')
        self.spc_incomplete_indicator = attributes[:'spcIncompleteIndicator']
      end

      if attributes.has_key?(:'version')
        self.version = attributes[:'version']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] authentication_id Value to be assigned
    def authentication_id=(authentication_id)
      @authentication_id = authentication_id
    end

    # Custom attribute writer method with validation
    # @param [Object] method Value to be assigned
    def method=(method)
      @method = method
    end

    # Custom attribute writer method with validation
    # @param [Object] phone_number Value to be assigned
    def phone_number=(phone_number)
      @phone_number = phone_number
    end

    # Custom attribute writer method with validation
    # @param [Object] email Value to be assigned
    def email=(email)
      @email = email
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          authentication_id == o.authentication_id &&
          method == o.method &&
          mfa_successful == o.mfa_successful &&
          phone_number == o.phone_number &&
          email == o.email &&
          other == o.other &&
          three_ds_requestor_id == o.three_ds_requestor_id &&
          three_ds_requestor_name == o.three_ds_requestor_name &&
          challenge == o.challenge &&
          decoupled_indicator == o.decoupled_indicator &&
          decoupled_max_time == o.decoupled_max_time &&
          three_ri_indicator == o.three_ri_indicator &&
          authentication_indicator == o.authentication_indicator &&
          authentication_date == o.authentication_date &&
          language_preference == o.language_preference &&
          spc_support == o.spc_support &&
          spc_incomplete_indicator == o.spc_incomplete_indicator &&
          version == o.version
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [authentication_id, method, mfa_successful, phone_number, email, other, three_ds_requestor_id, three_ds_requestor_name, challenge, decoupled_indicator, decoupled_max_time, three_ri_indicator, authentication_indicator, authentication_date, language_preference, spc_support, spc_incomplete_indicator, version].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{self.class.json_map[key]}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{self.class.json_map[key]}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CyberSource.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
