=begin
#CyberSource Merged Spec

#All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.38
=end

require 'date'

module CyberSource
  class UnifiedriskPaymentCardTokenDetails
    # Token provider type: network_token or merchant_token      Possible values: - network_token - merchant_token
    attr_accessor :provider_type

    # Type of payment credential being used. Visa, MasterCard, AMEX
    attr_accessor :type

    # Transient Token JWT ID
    attr_accessor :jti

    # Token number replacing PAN    
    attr_accessor :number

    # Token expiration month    
    attr_accessor :expiration_month

    # Token expiration year    
    attr_accessor :expiration_year

    # BIN from underlying card    
    attr_accessor :bin

    # Last 4 digits of card    
    attr_accessor :last4

    # Combined expiration date of the network token in MMYYYY format, used when the token's lifecycle is managed separately from the underlying PAN
    attr_accessor :expiration_date

    # Unique identifier of the token requestor (e.g., merchant or PSP) registered with the token service provider for DPAN provisioning and lifecycle management
    attr_accessor :requestor_id

    # A cryptographic value generated during tokenization (TAVV or CAVV) that authenticates the token for a specific transaction, preventing token replay attacks
    attr_accessor :cryptogram

    # Current lifecycle status of the network token (e.g., ACTIVE, SUSPENDED, DEACTIVATED). Tokens that are not ACTIVE should not be used for payment
    attr_accessor :status

    # Indicates the validity or expiry state of the cryptogram, helping detect stale or replayed token authentication attempts
    attr_accessor :cryptogra_validity

    # Indicates the authentication assurance level of the token provisioning process (e.g., APP_VERIFIED, CARDHOLDER_VERIFIED), impacting liability shift decisions
    attr_accessor :assurance_method

    # Supplementary data associated with the network token, such as merchant category restrictions, wallet provider metadata, or tokenization service payload extensions
    attr_accessor :additional_data

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'provider_type' => :'providerType',
        :'type' => :'type',
        :'jti' => :'jti',
        :'number' => :'number',
        :'expiration_month' => :'expirationMonth',
        :'expiration_year' => :'expirationYear',
        :'bin' => :'bin',
        :'last4' => :'last4',
        :'expiration_date' => :'expirationDate',
        :'requestor_id' => :'requestorId',
        :'cryptogram' => :'cryptogram',
        :'status' => :'status',
        :'cryptogra_validity' => :'cryptograValidity',
        :'assurance_method' => :'assuranceMethod',
        :'additional_data' => :'additionalData'
      }
    end

    # Attribute mapping from JSON key to ruby-style variable name.
    def self.json_map
      {
        :'provider_type' => :'provider_type',
        :'type' => :'type',
        :'jti' => :'jti',
        :'number' => :'number',
        :'expiration_month' => :'expiration_month',
        :'expiration_year' => :'expiration_year',
        :'bin' => :'bin',
        :'last4' => :'last4',
        :'expiration_date' => :'expiration_date',
        :'requestor_id' => :'requestor_id',
        :'cryptogram' => :'cryptogram',
        :'status' => :'status',
        :'cryptogra_validity' => :'cryptogra_validity',
        :'assurance_method' => :'assurance_method',
        :'additional_data' => :'additional_data'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'provider_type' => :'String',
        :'type' => :'String',
        :'jti' => :'String',
        :'number' => :'String',
        :'expiration_month' => :'String',
        :'expiration_year' => :'String',
        :'bin' => :'String',
        :'last4' => :'String',
        :'expiration_date' => :'String',
        :'requestor_id' => :'String',
        :'cryptogram' => :'String',
        :'status' => :'String',
        :'cryptogra_validity' => :'String',
        :'assurance_method' => :'String',
        :'additional_data' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'providerType')
        self.provider_type = attributes[:'providerType']
      end

      if attributes.has_key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.has_key?(:'jti')
        self.jti = attributes[:'jti']
      end

      if attributes.has_key?(:'number')
        self.number = attributes[:'number']
      end

      if attributes.has_key?(:'expirationMonth')
        self.expiration_month = attributes[:'expirationMonth']
      end

      if attributes.has_key?(:'expirationYear')
        self.expiration_year = attributes[:'expirationYear']
      end

      if attributes.has_key?(:'bin')
        self.bin = attributes[:'bin']
      end

      if attributes.has_key?(:'last4')
        self.last4 = attributes[:'last4']
      end

      if attributes.has_key?(:'expirationDate')
        self.expiration_date = attributes[:'expirationDate']
      end

      if attributes.has_key?(:'requestorId')
        self.requestor_id = attributes[:'requestorId']
      end

      if attributes.has_key?(:'cryptogram')
        self.cryptogram = attributes[:'cryptogram']
      end

      if attributes.has_key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.has_key?(:'cryptograValidity')
        self.cryptogra_validity = attributes[:'cryptograValidity']
      end

      if attributes.has_key?(:'assuranceMethod')
        self.assurance_method = attributes[:'assuranceMethod']
      end

      if attributes.has_key?(:'additionalData')
        self.additional_data = attributes[:'additionalData']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] jti Value to be assigned
    def jti=(jti)
      @jti = jti
    end

    # Custom attribute writer method with validation
    # @param [Object] number Value to be assigned
    def number=(number)
      @number = number
    end

    # Custom attribute writer method with validation
    # @param [Object] expiration_month Value to be assigned
    def expiration_month=(expiration_month)
      @expiration_month = expiration_month
    end

    # Custom attribute writer method with validation
    # @param [Object] expiration_year Value to be assigned
    def expiration_year=(expiration_year)
      @expiration_year = expiration_year
    end

    # Custom attribute writer method with validation
    # @param [Object] bin Value to be assigned
    def bin=(bin)
      @bin = bin
    end

    # Custom attribute writer method with validation
    # @param [Object] last4 Value to be assigned
    def last4=(last4)
      @last4 = last4
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          provider_type == o.provider_type &&
          type == o.type &&
          jti == o.jti &&
          number == o.number &&
          expiration_month == o.expiration_month &&
          expiration_year == o.expiration_year &&
          bin == o.bin &&
          last4 == o.last4 &&
          expiration_date == o.expiration_date &&
          requestor_id == o.requestor_id &&
          cryptogram == o.cryptogram &&
          status == o.status &&
          cryptogra_validity == o.cryptogra_validity &&
          assurance_method == o.assurance_method &&
          additional_data == o.additional_data
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [provider_type, type, jti, number, expiration_month, expiration_year, bin, last4, expiration_date, requestor_id, cryptogram, status, cryptogra_validity, assurance_method, additional_data].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{self.class.json_map[key]}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{self.class.json_map[key]}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CyberSource.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
