=begin
#CyberSource Merged Spec

#All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'uri'

module CyberSource
  class AuthenticationExemptionsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default, config)
      @api_client = api_client
	  @api_client.set_configuration(config)
    end
    # Authentication Exemptions Service
    # A new CYBS branded service to connect to VISA’s REST API to enable Visa Transaction Advisor (VTA) as a standalone service for merchants to support PSD2/SCA adoption and exemptions processing startegy in Europe.VTA Provides intelligent risk data to merchants as inputs to their in-house fraud management tools for fraud mitigation on Visa transactions. 
    # @param authentication_exemptions_request 
    # @param [Hash] opts the optional parameters
    # @return [RiskV1AuthenticationExemptionsPost201Response]
    def authentication_exemptions(authentication_exemptions_request, opts = {})
      data, status_code, headers = authentication_exemptions_with_http_info(authentication_exemptions_request, opts)
      return data, status_code, headers
    end

    # Authentication Exemptions Service
    # A new CYBS branded service to connect to VISA’s REST API to enable Visa Transaction Advisor (VTA) as a standalone service for merchants to support PSD2/SCA adoption and exemptions processing startegy in Europe.VTA Provides intelligent risk data to merchants as inputs to their in-house fraud management tools for fraud mitigation on Visa transactions. 
    # @param authentication_exemptions_request 
    # @param [Hash] opts the optional parameters
    # @return [Array<(RiskV1AuthenticationExemptionsPost201Response, Fixnum, Hash)>] RiskV1AuthenticationExemptionsPost201Response data, response status code and response headers
    def authentication_exemptions_with_http_info(authentication_exemptions_request, opts = {})
      
	  if @api_client.config.debugging
	  	begin
			raise
				@api_client.config.logger.debug 'Calling API: AuthenticationExemptionsApi.authentication_exemptions ...'
			rescue
				puts 'Cannot write to log'
			end
      end
      # verify the required parameter 'authentication_exemptions_request' is set
      if @api_client.config.client_side_validation && authentication_exemptions_request.nil?
        fail ArgumentError, "Missing the required parameter 'authentication_exemptions_request' when calling AuthenticationExemptionsApi.authentication_exemptions"
      end
      # resource path
      local_var_path = 'risk/v1/authentication-exemptions'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/hal+json;charset=utf-8'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json;charset=utf-8'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(authentication_exemptions_request)
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'RiskV1AuthenticationExemptionsPost201Response')
      if @api_client.config.debugging
		begin
		raise
			@api_client.config.logger.debug "API called: AuthenticationExemptionsApi#authentication_exemptions\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
		rescue
			puts 'Cannot write to log'
		end
	  end
      return data, status_code, headers
    end
  end
end
